def backendImage = ''
def frontendImage = ''
pipeline {

  agent {
      label 'jenkins-slave'
  }

  stages {
    stage('Cloning Git') {
      steps {
        git branch: 'main', url: 'https://github.com/awonyu9/devops-tp-2024-2025.git'
      }
    }
    stage('Building backend image') {
      steps {
        script {
          dir('TP-1/backend') {
            backendImage = docker.build("efrei2023/backend:1")

          }
        }
      }
    }
    stage('Publish backend Image') {
      steps {
        script {
          withDockerRegistry(credentialsId: 'docker') {
            backendImage.push()
          }

        }
      }
    }

    stage('Building frontend image') {
      steps {
        script {
          dir('TP-1/frontend') {
            frontendImage = docker.build("efrei2023/frontend:1")
          }
        }
      }
    }

    stage('Publish frontend Image') {
      steps {
        script {
          withDockerRegistry(credentialsId: 'docker') {
            frontendImage.push()
          }
        }
      }
    }

    stage('Deploy backend container') {
      steps {
        echo "Run backend container "
        sh 'docker run -d --net=efrei -e POSTGRES_PASSWORD=postgres --name backend efrei2023/backend:1'
      }
    }
    stage('Deploy frontend container') {
      steps {
        echo "Run  frontend container"
        sh 'docker run -d --net=efrei  -p 8081:80 -e POSTGRES_PASSWORD=postgres --name frontend efrei2023/frontend:1'
        input message: 'Done using the app? Click "Proceed" to continue.'
        sh 'docker stop backend frontend'
        sh 'docker rm backend frontend'
      }
    }
  }
}
